#!/usr/bin/env bash

# how to use 'read'
# https://stackoverflow.com/questions/1885525/how-do-i-prompt-a-user-for-confirmation-in-bash-script



# Prompts user for path to file
echo "Enter File Path:"
read -r file1_path
if [ -z "$file1_path" ]
then
    echo "No file path provided"
else

    #Converts Windows directory to Bash directory structure
    wsl_path=$(wslpath -a $file1_path)

    echo WSL Path is $wsl_path

    #Generates md5 for file with directory removed
    #echo "MD5 Checksum of file 1 is "$(md5sum $wsl_path) | cut -c1-58
    checksum_1=$(md5sum $wsl_path | cut -c1-32)
    echo "Checksum 1 is $checksum_1"

    #Prompt user to select either a different file or manually enter a checksum to compare with
    echo "What are you comparing this checksum to?"
    PS3='Please select: '
    options=("File" "Checksum" "Quit")
    select opt in "${options[@]}"
    do
        case $opt in 
            "File")
                echo "Enter File Path:"
                read -r file2_path
                wsl2_path=$(wslpath -a $file2_path)
                #echo "MD5 Checksum of file 2 is "$(md5sum $wsl2_path) | cut -c1-58
                checksum_2=$(md5sum $wsl2_path | cut -c1-32)
                echo "Checksum 2 is $checksum_2"
                break
                ;;
            "Checksum")
                echo "Enter Checksum:"
                read -r checksum_2
                break
                ;;
            "Quit")
                break
                ;;
            *) echo "invalid option $REPLY";;
        esac
    done

    if [ "$checksum_1" = "$checksum_2" ]; then
        echo "Checksums match, yay!"
    else
        echo "Checksums don't match, boo!" 
    fi
fi