#!/usr/bin/env bash

############################################################
# MIT License                                              #
############################################################

MIT()
{
    echo ""
    echo "Copyright 2021 Jameson Feakes"
    echo ""
    echo "Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:"
    echo ""
    echo "The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software."
    echo ""
    echo "THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE."
    echo ""
}

############################################################
# Help                                                     #
############################################################
Help()
{
   # Display Help
   echo ""
   echo "This script compares the MD5 hash of a file against another file, or a user inputted checksum"
   echo "It is made to be used on Windows files in WSL or with GitBash"
   echo
   echo "Syntax: ./md5compare [-m|h|f|c]"
   echo "options:"
   echo "-m     Print the MIT license notification."
   echo "-h     Print this Help."
   echo "-f     To compare the MD5 of one file against another"
   echo "       USAGE: -f 'path/to/file/'"
   echo "       NOTE: Filepath must be in quotations"
   echo "-c     Compare against a user inputted checksum"
   echo "       USAGE: -c 'path/to/file/'"
   echo "       NOTE: Filepath must be in quotations"
   echo ""
}

############################################################

compare_files ()
{
    #Compare the md5 checksums of 2 files
    wsl_path=$(wslpath -a $file1_path)
    checksum_1=$(md5sum $wsl_path | cut -c1-32)

    echo "Enter Path to the file you want to compare to: "
    read -r file2_path
    wsl2_path=$(wslpath -a $file2_path)
    #echo "MD5 Checksum of file 2 is "$(md5sum $wsl2_path) | cut -c1-58
    checksum_2=$(md5sum $wsl2_path | cut -c1-32)

    if [ "$checksum_1" = "$checksum_2" ]; then
    echo ""
    echo "------------------------------"
    echo "$checksum_1  -Checksum of File 1"
    echo "$checksum_2  -Checksum of File 2"
    echo ""
    echo "Checksums match, yay!"
    echo "------------------------------"
    else
    echo ""
    echo "------------------------------"
    echo "$checksum_1  -Checksum of File 1"
    echo "$checksum_2  -Checksum of File 2"
    echo ""
    echo "Checksums don't match, boo!" 
    echo "------------------------------"
    fi
}

compare_checksum ()
{
    wsl_path=$(wslpath -a $file1_path)
    checksum_1=$(md5sum $wsl_path | cut -c1-32)

    echo "Enter the MD5 hash you wish to compare this file to: "
    read -r checksum
    if [ "$checksum_1" = "$checksum" ]; then
        echo ""
        echo "------------------------------"
        echo "$checksum_1  -Checksum of your file"
        echo "$checksum  -Checksum provided"
        echo ""
        echo "Checksums match, yay!"
        echo "------------------------------"
    else
        echo ""
        echo "------------------------------"
        echo "$checksum_1  -Checksum of your file"
        echo "$checksum  -Checksum provided"
        echo ""
        echo "Checksums don't match, boo!"
        echo "------------------------------"
    fi
}

############################################################
# Main program                                             #
############################################################

#Get the options
while getopts ":mhf:c:" option; do
    case $option in
        m)
           # display MIT License
           MIT
           exit;;

        h) # display Help
            Help
            exit;;

        f) # Enter a File Path for the 2nd file
            file1_path=$OPTARG
            compare_files
            exit;;

        c) #Enter a checksum to compare to the file you provided
            file1_path=$OPTARG
            compare_checksum
            exit;;

        \?) # Invalid option
            echo "Error: Invalid option"
            exit;;
    esac
done

Help